<a href="https://colab.research.google.com/github/ParichayaHongthongkum/data_viz_2022/blob/main/FinalExam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Final Exam: งานกลุ่ม Final ที่อาจารย์สุ่มให้**


1.  ให้นักศึกษาสร้าง Dashboard แสดงรายงานเกี่ยวกับข้อมูลการตรวจโรค(ov) จาก ไฟล์  alldb.csv และ hospital_list.xlsx
2.   โดยข้อมูลหลักจะอยู่ใน ตาราง alldb.csv (ข้อมูลที่สมบูรณ์ที่สามารถนำมาใช้งานได้ต้องมีค่าใน column ต่อไปนี้ดังนี้

     
* user เป็นตัวเลข 5 หลัก (ตัวเลขเท่านั้น)
* RowKey เป็น String
* date เป็น YYYY-MM-DD
* phone เป็น String
* site เป็นตัวเลข 5 หลัก (ตัวเลขเท่านั้น)
* time เป็น hh-mm-ss
* urine มีค่า String
* ov เป็นตัวเลข มีค่าตั้งแต่ 0-4 (0 คือไม่พบโรค 1-4 คือพบโรคที่ระดับความรุนแรงต่างๆ)
* PartitionKey เป็นตัวเลข 5 หลัก (ตัวเลขเท่านั้น))

3. ไฟล์ alldb.csv และ hospital_list.xlsx สามารถถูกเชื่อมโยงกันโดย site ในไฟล์ alldb.csv คือ hcode ในไฟล์ hospital_list.xlsx

โดยข้อมูลสำคัญที่ต้องแสดงคือ

* จำนวนการตรวจในแต่ละพื้นที่ (จังหวัด-อำเภอ ในไฟล์ hospital_list.xlsx) เทียบกับ จำนวนที่พบโรค (column ov ในไฟล์ alldb.csv)
* ช่วงเวลาที่ตรวจ (date ในไฟล์ alldb.csv)
* อื่นๆที่นักศึกษาเห็นว่าเป็นประโยชน์ (phone (ชนิดโทรศัพท์ที่ใช้บันทึก), title (คำนำหน้าชื่อ), age (อายุ))

(คิดคะแนนตามกลุ่ม final โดยไฟล์ที่ทุกคนในกลุ่มต้องมีคือไฟล์ data pre-processing และ link ไปที่ Dashboard ที่สร้่างโดยเปิดให้สามารถเข้าไปดูและใช้งานได้)
ส่งไม่เกิน 23.59 วันจันทร์ที่ 11 เมษายน 2565

#Load data

In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
data1= pd.read_csv('/content/drive/MyDrive/ovrdt data/alldb.csv')  ## สร้างตัวแปร รับค่าข้อมูลที่อยู่ใน Google drive
data1 ## แสดงข้อมูล

,Unnamed: 0,user,RowKey,care,date,ov,phone,site,time,urine,pid,PartitionKey,title,age
0,0,test,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,data is not completed,data is not completed
1,1,04857,136FD222-FD9F-4E54-AE1F-7282A276B085,NaN,2022-02-24,NaN,"iPhone10,4",05310,10:50:32,NaN,NaN,NaN,data is not completed,data is not completed
2,2,NaN,1E6D3D62-4C8A-4F8E-90D1-0DC5BC2752DF.png,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,data is not completed,data is not completed
3,3,3450101576642,2D331FB0-CBA2-4586-A5B0-CB3CF44DD9FE,NaN,2022-02-23,0,"iPhone13,4",05087,09:59:47,ปกติ (เหลืองใส),NaN,NaN,data is not completed,data is not completed
4,4,3450101576642,45197AF7-7CB4-470C-9ABB-37C092BD6B21,NaN,2022-02-23,NaN,"iPhone13,4",05087,09:44:06,ปกติ (เหลืองใส),NaN,NaN,data is not completed,data is not completed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40030,40030,NaN,6B5FA20F-190E-4021-8547-C12308024C6C,NaN,NaN,NaN,"iPhone13,4",01234,NaN,NaN,5,เกษศิรินทร์ ไชยลาภ,data is not completed,data is not completed
40031,40031,NaN,F48C51C0-A345-40D6-93F4-46213267E1B1,NaN,NaN,2,"iPhone10,5",01234,NaN,ปกติ (เหลืองใส),5,เถลิงเกียรติ เสริฐเลิศ,data is not completed,data is not completed
40032,40032,NaN,A986BDAA-6D7C-4017-8E62-A3C104E946B9,NaN,NaN,1,"iPhone13,4",01234,NaN,ปกติ (เหลืองใส),1,เสรี,data is not completed,data is not completed
40033,40033,NaN,bbuogxulur.png,NaN,NaN,NaN,Samsung SM-A115F,01234,NaN,NaN,1,เสรี,data is not completed,data is not completed
40034,40034,NaN,zttpqogiso.png,NaN,NaN,1,Samsung SM-A115F,01234,NaN,ปกติ (เหลืองใส),1,เสรี,data is not completed,data is not completed

In [4]:
data2= pd.read_excel('/content/drive/MyDrive/ovrdt data/hospital_list.xlsx')  ## สร้างตัวแปร รับค่าข้อมูลที่อยู่ใน Google drive
data2 ## แสดงข้อมูล

,hcode,name,zone_code,zone_name,provincecode,province,amphurcode,amphur,tamboncode,tambon,code4,name5,code9,name10,short_thai,short_english
0,00001,สำนักงานสาธารณสุขจังหวัดสมุทรปราการ,6,สาขาพื้นที่(ระยอง),11.0,สมุทรปราการ,1.0,เมืองสมุทรปราการ,1.0,ปากน้ำ,1.0,สำนักงานสาธารณสุขจังหวัด,NaN,NaN,สป,SPK
1,00002,สำนักงานสาธารณสุขจังหวัดนนทบุรี,4,สาขาพื้นที่(สระบุรี),12.0,นนทบุรี,1.0,เมืองนนทบุรี,4.0,บางกระสอ,1.0,สำนักงานสาธารณสุขจังหวัด,NaN,NaN,นบ,NBI
2,00003,สำนักงานสาธารณสุขจังหวัดปทุมธานี,4,สาขาพื้นที่(สระบุรี),13.0,ปทุมธานี,1.0,เมืองปทุมธานี,1.0,บางปรอก,1.0,สำนักงานสาธารณสุขจังหวัด,NaN,NaN,ปท,PTE
3,00004,สำนักงานสาธารณสุขจังหวัดพระนครศรีอยุธยา,4,สาขาพื้นที่(สระบุรี),14.0,พระนครศรีอยุธยา,1.0,พระนครศรีอยุธยา,3.0,หอรัตนไชย,1.0,สำนักงานสาธารณสุขจังหวัด,NaN,NaN,อย,AYA
4,00005,สำนักงานสาธารณสุขจังหวัดอ่างทอง,4,สาขาพื้นที่(สระบุรี),15.0,อ่างทอง,1.0,เมืองอ่างทอง,8.0,บ้านอิฐ,1.0,สำนักงานสาธารณสุขจังหวัด,NaN,NaN,อท,ATG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17098,99990,ศูนย์สุขภาพชุมชนโรงพยาบาลอุตรดิตถ์(สาขา 2 วัดท...,2,สาขาพื้นที่(พิษณุโลก),53.0,อุตรดิตถ์,1.0,เมืองอุตรดิตถ์,1.0,ท่าอิฐ,8.0,ศูนย์สุขภาพชุมชน ของ รพ.,10.0,1 ปฐมภูมิ,อต,UTT
17099,99991,ศูนย์สุขภาพชุมชนโรงพยาบาลกุยบุรี,5,สาขาพื้นที่(ราชบุรี),77.0,ประจวบคีรีขันธ์,2.0,กุยบุรี,1.0,กุยบุรี,8.0,ศูนย์สุขภาพชุมชน ของ รพ.,10.0,1 ปฐมภูมิ,ปข,PKN
17100,99993,ศูนย์สุขภาพชุมชนตำบลวัดเพลง,5,สาขาพื้นที่(ราชบุรี),70.0,ราชบุรี,9.0,วัดเพลง,3.0,วัดเพลง,8.0,ศูนย์สุขภาพชุมชน ของ รพ.,10.0,1 ปฐมภูมิ,รบ,RBR
17101,99996,คลินิกทันตกรรม สสจ.ศรีสะเกษ,10,สาขาพื้นที่(อุบลราชธานี),33.0,ศรีสะเกษ,1.0,เมืองศรีสะเกษ,11.0,โพนข่า,8.0,ศูนย์สุขภาพชุมชน ของ รพ.,10.0,1 ปฐมภูมิ,ศก,SSK
17102,99998,ศูนย์สุขภาพชุมชนตำบลบางแพ,5,สาขาพื้นที่(ราชบุรี),70.0,ราชบุรี,6.0,บางแพ,2.0,วังเย็น,8.0,ศูนย์สุขภาพชุมชน ของ รพ.,10.0,1 ปฐมภูมิ,รบ,RBR